config/routes.rb
Rails.application.routes.draw do
  resources :books do 
  	resources :comments, only: [:create, :destroy]
  	resources :votes
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :votes
	has_many :links
	has_many :comments

	validates :title, :author, presence: true
	validates :title, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :book
	belongs_to :commenter, class_name: 'User'

	validates :text, :book_id, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
	belongs_to :book

	validates :book_id, :link, presence: true
	validates :book_id, :link, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :votes

	validates :username, :email, :password, presence: true
	validates :username, :email, uniqueness: true
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user 
	belongs_to :book

	validates :user_id, :book_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :log_in, :logged_in?, :current_user, :authorized?

  def log_in
    session[:user_id] = user.id
  end

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    return nil if !logged_in?
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authorized?(integer_id)
    session[:user_id] == integer_id.to_i
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index 
		@books = Book.order(rank: :desc, title: :asc).limit 100
	
	end

	def show
		@book = Book.find(params[:id])
		
		links = @book.links
		@link = links[0].link.html_safe	
	end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		user = User.find(session[:user_id])
		@book= Book.find(params[:book_id])
		@comment = @book.comments.new(comment_params)
		@comment.commenter_id = user.id

		if @comment.save
			redirect_to book_path(@book)
		else
			@errors = ["Comments Cant be blank"]
			redirect_to book_path(@book)
		end
	end

	def destroy
		@comment = Comment.find(params[:id]).destroy
		redirect_to book_path(@comment.book)
	end

	private
	def comment_params
		params.require(:comment).permit(:text)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:sessions][:email])
		if user && user.authenticate(params[:sessions][:password])
			session[:user_id] = user.id 
			redirect_to root_path
		else
			@errors = ["Invalid email/password combination"]
			render new_session_path
		end
	end

	def destroy
		session.destroy
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id 
			redirect_to root_path
		else
			@errors = @user.errors.full_messages
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def create
		user = User.find(session[:user_id])
		@book = Book.find(params[:book_id])
		@vote = @book.votes.create(user_id: user.id)

		redirect_to book_path(@book)
	end

	def destroy
		vote = Vote.find(params[:id]).destroy

		redirect_to book_path(params[:book_id])
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def user_can_vote?(book_id)
    book = Book.find(book_id)
  	book.votes.each do |vote|
  		return false if vote.user_id == session[:user_id]
  	end
  	return true
  end

  def return_user_vote_id(book_id)
  	user = User.find(session[:user_id])
  	vote = user.votes.where(["book_id = ?", book_id])
  	vote[0].id
 
  end
end

app/views/books/index.html.erb
<h1>The Greatest Books of all Space and Time!</h1>
<div class='row'>
	
	<% @books.each do |book| %>
		<div class="col s6 offset-s1">
			<%= link_to book.title, book_path(book) %> By: <%= book.author %> Rank: <%= book.rank %>
		</div>	
			
	<% end %>
</div>
	

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h4>Support this page by clicking on the picture and purchasing anything from amazon</h4>
<div class='row'>
	<div class='col 1 offset-s4'><%= @link %></div>
</div>

<div class='row'>
	<div class='col 3 offset-s4'><%= render 'comments/comment' %></div>
</div>
<div class='row'>
	<div class='col 3 offset-s4'><h5> Upvote Count : <%= @book.votes.count %></h5></div>
</div>
<div class='row'>
	<div class='col 3 offset-s4'><h3>Add Comment</h3></div>
</div>	
	<% if !logged_in? %>
		<div class='row'>
			<div class='col 3 offset-s4'><h3>Log in to add comment or Upvote</h3></div>
			
		</div>
	<% else %>
		<div class='row'>
			<div class='col 3 offset-s4'><%= render 'votes/vote' %></div>
		</div>		

		<div class='row'>
			<div class='col 3 offset-s4'><%= render 'comments/form' %></div>	
		</div>	
	<% end %>

app/views/comments/_comment.html.erb
<% if @book.comments %>
	<% @book.comments.each do |comment| %>
		<p>Username: <strong><%= comment.commenter.username %></strong></p>
		<p><%= comment.text %></p>

		<% if authorized?(comment.commenter_id) %>
			<%= link_to 'Remove Comment', [comment.book, comment], method: :delete, data: {confirm: "Are you sure you want to delete this comment?"} %>
		<% end %>
	<% end %>
<% end %>

app/views/comments/_form.html.erb
	<%= form_for ([@book, @book.comments.build]) do |f| %>
		<p>
			<%= f.label :text %><br>
			<%= f.text_area :text %>
		</p>
		<p>
			<%= f.submit %>
		</p>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <div class="nav-wrapper">
      <%= link_to "Home", root_path %>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
      <% if logged_in? %>
        <li><%= link_to "Log Out", session_path(current_user), method: :delete %></li>
      <% else %>
        <li><%= link_to "Register", new_user_path %></li>
        <li><%= link_to "Log In", new_session_path%></li>
      <% end %>
      </ul>
    </div>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= render partial: './errors', locals: {errors: @errors} %>

<%= form_for :user, url: '/users' do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.submit %>
<% end %>

app/views/votes/_vote.html.erb
	<% if user_can_vote?(@book.id) %>
		<%= form_for ([@book, @book.votes.build]) do |f| %>
			<p> <%= f.submit %></p>
		<% end %>
	<% else %>
		<%= link_to 'Remove vote', book_vote_path(@book,return_user_vote_id(@book)), method: :delete %>
	<% end %>